apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/zeenmc/argo-git-ops.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: eni-pov
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - CreateNamespace=true
