apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-projects-and-apps-dev
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/brokenbytedev/gitops-argp.git
    targetRevision: main
    path: ./argo-projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
