apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store-azure-dev
  namespace: argocd
spec:
  project: dev-platform

  source:
    repoURL: oci://mcr.microsoft.com/oss/kubernetes-csi/secrets-store/azure-secrets-store
    chart: azure-secrets-store
    targetRevision: 1.5.0
    helm:
      values: |
        windows:
          enabled: false

        syncSecret:
          enabled: true

        rotationPollInterval: 2m
        enableSecretRotation: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
