apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-csi-secrets-store-dev
  namespace: argocd
spec:
  project: dev-platform

  source:
    repoURL: oci://mcr.microsoft.com/oss/azure/secrets-store-csi-driver-provider-azure/charts
    chart: secrets-store-csi-driver-provider-azure
    targetRevision: 1.6.1
    helm:
      values: |
        windows:
          enabled: false

        syncSecret:
          enabled: true

        enableSecretRotation: true
        rotationPollInterval: 2m

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
