apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-csi-secrets-store-dev
  namespace: argocd
spec:
  project: dev-platform

  source:
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    chart: azure-kv/csi-secrets-store-provider-azure
    targetRevision: 1.7.2
    helm:
      values: |
        windows:
          enabled: false
        syncSecret:
          enabled: true
        enableSecretRotation: true
        rotationPollInterval: 2m
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
