apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-platform
  namespace: argocd
spec:
  description: "DEV Platform project"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "parkaero"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
