apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-platform
  namespace: argocd
spec:
  description: "DEV GitOps project"
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc

  sourceRepos:
  - https://github.com/brokenbytedev/argocd.gitops.git
  - https://traefik.github.io/charts
  - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  - oci://mcr.microsoft.com/oss/kubernetes-csi/secrets-store/azure-secrets-store
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"